export const ALLATLISTA = [
  {
    fajnev: "Oroszlán",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 14,
    erdekesseg: "Az oroszlánok csapatban, úgynevezett falkában élnek.",
  },
  {
    fajnev: "Afrikai elefánt",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna és erdőségek",
    atlageletkor: 60,
    erdekesseg: "A legnagyobb szárazföldi állat, agyarai egész életében nőnek.",
  },
  {
    fajnev: "Zebra",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 25,
    erdekesseg: "Minden zebra csíkja egyedi, mint az emberi ujjlenyomat.",
  },
  {
    fajnev: "Zsiráf",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 25,
    erdekesseg: "A legmagasabb szárazföldi állat, nyaka akár 2 méter hosszú is lehet.",
  },
  {
    fajnev: "Kenguru",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "ausztrál szavanna és erdőségek",
    atlageletkor: 8,
    erdekesseg: "Az erszényesek közé tartozik, és képes akár 9 métert is ugrani egyetlen szökelléssel.",
  },
  {
    fajnev: "Jegesmedve",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "sarkvidéki jégtakarók",
    atlageletkor: 25,
    erdekesseg: "Bundája valójában áttetsző, a szőrszálak belseje üreges, ami kiváló hőszigetelést biztosít.",
  },
  {
    fajnev: "Császárpingvin",
    kep: "kepek/placeholder.png",
    tipus: "madár",
    elohely: "Antarktisz",
    atlageletkor: 20,
    erdekesseg: "A legnagyobb termetű pingvinfaj, a hímek akár 60 napig is böjtölnek a tojások keltetése közben.",
  },
  {
    fajnev: "Gólya",
    kep: "kepek/placeholder.png",
    tipus: "madár",
    elohely: "európai és ázsiai vizes élőhelyek",
    atlageletkor: 20,
    erdekesseg: "Hűséges párválasztó, gyakran visszatér ugyanabba a fészekbe, amelyet akár évekig is használ.",
  },
  {
    fajnev: "Kardszárnyú delfin (Killer Whale)",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "óceánok világszerte",
    atlageletkor: 50,
    erdekesseg: "Valójában a delfinfélék családjába tartozik, és összetett társadalmi struktúrában él.",
  },
  {
    fajnev: "Gepárd",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 12,
    erdekesseg: "A szárazföldi állatok leggyorsabbja, akár 120 km/h sebességet is elérhet rövid távon.",
  },
  {
    fajnev: "Barnamedve",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "észak-amerikai és eurázsiai erdőségek",
    atlageletkor: 25,
    erdekesseg: "Téli álmot alszik, de nem mélyen, könnyen felébredhet zavarás esetén.",
  },
  {
    fajnev: "Vörös róka",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "erdők, mezők, városi területek világszerte",
    atlageletkor: 4,
    erdekesseg: "Rendkívül alkalmazkodóképes, városi környezetben is gyakran megjelenik.",
  },
  {
    fajnev: "Szürke farkas",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "erdők, tundrák, füves puszták",
    atlageletkor: 8,
    erdekesseg: "Falkában vadászik, összetett kommunikációs rendszerrel rendelkezik (testbeszéd, vonyítás).",
  },
  {
    fajnev: "Kék bálna",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "óceánok világszerte",
    atlageletkor: 80,
    erdekesseg: "A Föld valaha élt legnagyobb állata, szíve akkora, mint egy kisautó.",
  },
  {
    fajnev: "Pápaszemes medve",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "dél-amerikai Andok",
    atlageletkor: 20,
    erdekesseg: "Az egyetlen Dél-Amerikában őshonos medvefaj, nevéhez hűen szeme körül jellegzetes mintázat van.",
  },
];