export const ALLATLISTA = [
  {
    fajnev: "Oroszlán",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 14,
    erdekesseg: "Az oroszlánok csapatban, úgynevezett falkában élnek.",
  },
  {
    fajnev: "Afrikai elefánt",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna és erdőségek",
    atlageletkor: 60,
    erdekesseg: "A legnagyobb szárazföldi állat, agyarai egész életében nőnek.",
  },
  {
    fajnev: "Császárpingvin",
    kep: "kepek/placeholder.png",
    tipus: "madár",
    elohely: "Antarktisz partvidéke",
    atlageletkor: 20,
    erdekesseg: "A hímek akár 60 napig is böjtölnek a tojás keltetése közben.",
  },
  {
    fajnev: "Gólya",
    kep: "kepek/placeholder.png",
    tipus: "madár",
    elohely: "európai és ázsiai vizes élőhelyek",
    atlageletkor: 20,
    erdekesseg: "Hűséges párválasztó, gyakran visszatér ugyanabba a fészekbe.",
  },
  {
    fajnev: "Királykobra",
    kep: "kepek/placeholder.png",
    tipus: "hüllő",
    elohely: "Délkelet-Ázsia esőerdei",
    atlageletkor: 20,
    erdekesseg:
      "A világ leghosszabb mérges kígyója, akár 5,5 métert is elérhet.",
  },
  {
    fajnev: "Zöld tengeri teknős",
    kep: "kepek/placeholder.png",
    tipus: "hüllő",
    elohely: "trópusi és szubtrópusi tengerek",
    atlageletkor: 80,
    erdekesseg: "Több ezer kilométert vándorol a tojásrakás helyszínére.",
  },
  {
    fajnev: "Krokodil",
    kep: "kepek/placeholder.png",
    tipus: "hüllő",
    elohely: "afrikai folyók és mocsarak",
    atlageletkor: 70,
    erdekesseg: "Állkapcsa hihetetlenül erős, de a száját nyitó izmai gyengék.",
  },
  {
    fajnev: "Foltos szalamandra",
    kep: "kepek/placeholder.png",
    tipus: "kétéltű",
    elohely: "nedves lombos erdők",
    atlageletkor: 20,
    erdekesseg: "Mérgező váladékot termel a bőrén a ragadozók ellen.",
  },
  {
    fajnev: "Vöröshasú unka",
    kep: "kepek/placeholder.png",
    tipus: "kétéltű",
    elohely: "Európai vizes élőhelyek",
    atlageletkor: 15,
    erdekesseg:
      "Hasa élénkvörös, ami figyelmezteti a ragadozókat, hogy mérgező.",
  },
  {
    fajnev: "Kék bálna",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "óceánok világszerte",
    atlageletkor: 80,
    erdekesseg:
      "A Föld valaha élt legnagyobb állata, szíve akkora, mint egy kisautó.",
  },
  {
    fajnev: "Tavi kecsege",
    kep: "kepek/placeholder.png",
    tipus: "hal",
    elohely: "európai folyók és tavak",
    atlageletkor: 22,
    erdekesseg: "Hosszú, lapát alakú orrával keresi a táplálékot az iszapban.",
  },
  {
    fajnev: "Clownfish (Bohóchal)",
    kep: "kepek/placeholder.png",
    tipus: "hal",
    elohely: "trópusi korallzátonyok",
    atlageletkor: 8,
    erdekesseg:
      "Szimbiózisban él tengerirózsákkal, amelyek védelmet nyújtanak neki.",
  },
  {
    fajnev: "Fehér cápa",
    kep: "kepek/placeholder.png",
    tipus: "hal",
    elohely: "óceánok világszerte",
    atlageletkor: 70,
    erdekesseg:
      "Kiváló szaglásával több kilométerről érzékeli a vér cseppjeit.",
  },
  {
    fajnev: "Jegesmedve",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "sarkvidéki jégtakarók",
    atlageletkor: 25,
    erdekesseg: "Bundája valójában áttetsző, a szőrszálak belseje üreges.",
  },
  {
    fajnev: "Vándorsólyom",
    kep: "kepek/placeholder.png",
    tipus: "madár",
    elohely: "világszerte, nyílt területeken",
    atlageletkor: 15,
    erdekesseg:
      "A világ leggyorsabb állata, zuhanórepülésben akár 300 km/h sebességet is elér.",
  },
  {
    fajnev: "Zebra",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 25,
    erdekesseg: "Minden zebra csíkja egyedi, mint az emberi ujjlenyomat.",
  },
  {
    fajnev: "Axolotl (Mexikói kétéltű)",
    kep: "kepek/placeholder.png",
    tipus: "kétéltű",
    elohely: "Mexikó édesvizei",
    atlageletkor: 15,
    erdekesseg:
      "Képes testrészeit újranöveszteni, beleértve a végtagokat és a szívet is.",
  },
  {
    fajnev: "Gepárd",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "afrikai szavanna",
    atlageletkor: 12,
    erdekesseg:
      "A szárazföldi állatok leggyorsabbja, akár 120 km/h sebességet is elérhet.",
  },
  {
    fajnev: "Komodói varánusz",
    kep: "kepek/placeholder.png",
    tipus: "hüllő",
    elohely: "Indonézia szigetei",
    atlageletkor: 30,
    erdekesseg: "A legnagyobb ma élő gyík, mérges harapással rendelkezik.",
  },
  {
    fajnev: "Pápaszemes medve",
    kep: "kepek/placeholder.png",
    tipus: "emlős",
    elohely: "dél-amerikai Andok",
    atlageletkor: 20,
    erdekesseg: "Az egyetlen Dél-Amerikában őshonos medvefaj.",
  },
];
